//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lesson()
        {
            this.UserInLessons = new HashSet<UserInLesson>();
        }
    
        public string lesson_id { get; set; }
        public string lesson_name { get; set; }
        public string lesson_days { get; set; }
        public Nullable<System.TimeSpan> lesson_start_time { get; set; }
        public Nullable<float> lesson_duration { get; set; }
        public Nullable<int> capacity { get; set; }
        public string instructor_name { get; set; }
        public string training_type { get; set; }
        public string gear { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInLesson> UserInLessons { get; set; }
    }
}
